### ISSUE TITLE
Support ios8

### ISSUE THREAD

**Issue by JasonWuGit** [SocialObjects-Software/SOMotionDetector#12]
it's perfect ,but i expert it's location can use in ios8 foreground and background

**Comment by yuxiangq** [comment]
yes,please support iOS8

**Comment by gorkemg** [comment]
Just add a new row into the app's plist file:
key: NSLocationWhenInUseUsageDescription
value: text with a description why location services is needed. 
For instance: "Location Services is used to calculate the movement of the device."

Finally, in SOLocationManager add: 
```objective-c
[self.locationManager requestWhenInUseAuthorization];
```
right after:
```objective-c
self.locationManager.delegate = self;
```
in the init method.

iOS 8 needs these adjustments.
