### ISSUE TITLE
 motionDetector.currentSpeed always 0

### ISSUE THREAD

**Issue by chary1n** [SocialObjects-Software/SOMotionDetector#16]
motionDetector.currentSpeed always 0

**Comment by arturdev** [comment]
On simulator or on the device?

**Comment by talisk** [comment]
Of course on the device. I have find the same issue. No matter which device I used. iPad Air with M7 chip or iPhone 5c without M7 chip.

**Comment by arturdev** [comment]
Can you check that also with the demo project please?

**Comment by lucaji** [comment]
I commented out this check and its working on iPhone 5c
    - (void)calculateMotionType
    {
        if (self.useM7IfAvailable && [SOMotionDetector motionHardwareAvailable]) {
            //return;
        }

**Comment by arturdev** [comment]
You can set `useM7IfAvailable` to `NO` instead
