### ISSUE TITLE
motionTypeChangedBlock does not fire when running in the background

### ISSUE THREAD

**Issue by SimplyKeshav** [SocialObjects-Software/SOMotionDetector#19]
Hi,

First things first, THANK YOU ! for this great library. Now to the question..., I am initiating SOMotionDetector in my App Delegate (didFinishLaunchingWithOptions). But when my app goes into background state, I do not get alerts.

My App Delegate --> didFinishLaunchingWithOptions contains:

... ... ... ...
    [SOMotionDetector sharedInstance].motionTypeChangedBlock = ^(SOMotionType motionType)
    {
        [myClass MotionTypeChanged: motionType];
    };
... ... ... ...

Is it something the software doesn't support or am I doing it wrong ?

**Comment by arturdev** [comment]
Are you sure that you have enabled background location updates?
