### ISSUE TITLE
Not Working in Background

### ISSUE THREAD

**Issue by extremechatter** [SocialObjects-Software/SOMotionDetector#22]
Hi, Thank you so much for your hard work.

I am trying to detect change in Activity type while the app is in background. It works perfectly in foreground but doesn't work in background. I have enabled background location update mode. 

Thank you for your help.

**Comment by arturdev** [comment]
Are you sure that you added `NSLocationAlwaysUsageDescription` key in you Info.plist file?

**Comment by extremechatter** [comment]
Yes. It asked for authorisation on first installed. Also checked the privacy of locations. The app is listed and shows: Always. Is there any code I need to put in application entered background option, in appdelegate?

**Comment by extremechatter** [comment]
I am just looking to find out when the state switches between not moving and automotive and then process a set of code accordingly. All this happens while the app is in background.

All your help will be appreciated.

Thank you

**Comment by johnnyshankman** [comment]
Is this iOS 9 problem?

It's because of this: https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates

We should add support for that in iOS 9.

**Comment by arturdev** [comment]
fixed
