### ISSUE TITLE
Doesn't Ask for Authorization

### ISSUE THREAD

**Issue by johnnyshankman** [SocialObjects-Software/SOMotionDetector#23]
At no point is there a call for `requestWhenInUseAuthorization` or `requestAlwaysAuthorization` for ios8 and ios9 support. I think this should either be asked upon `startDetection` and/or should be exposed to the developer to call whenever they see fit so that they can ask for it at the right time in their UX.

Either way this issue makes it really weird to get Core Location updates because we either have to edit your Pod or ask for it manually on an unused Location Manager instance.

**Comment by johnnyshankman** [comment]
This might be related to the fact that the readme tells me to download the wrong version of the repo?

**Comment by johnnyshankman** [comment]
Yeah can confirm that installing using Pods causes me to get a weird package. I don't have StepDetector or block support?

**Comment by arturdev** [comment]
Yes, it should be better if you download repo directly. 
I haven't updated pods yet.

**Comment by johnnyshankman** [comment]
@arturdev that makes sense thank you.

**Comment by johnnyshankman** [comment]
I think i'm going to open a separate issue for not being able to set backgroundLocation updates in iOS9 because we need to be able to set the CLLocationManager's property `allowsBackgroundLocationUpdates` to true.

https://developer.apple.com/library/prerelease/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates

https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/Objective-C/CoreLocation.html

I've made my own version that does this currently, it was a real easy update.
