### ISSUE TITLE
iOS9 Background Location Support

### ISSUE THREAD

**Issue by johnnyshankman** [SocialObjects-Software/SOMotionDetector#24]
Currently we cannot do background location updates with SOMotionDetector on iOS9

We have to expose a way to set the `allowsBackgroundLocationUpdates` property of the `SOLocationManager`'s instance of `CLLocationManager` to `YES` or `NO`.

https://developer.apple.com/library/prerelease/ios/releasenotes/General/iOS90APIDiffs/Objective-C/CoreLocation.html

https://developer.apple.com/library/prerelease/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/occ/instp/CLLocationManager/allowsBackgroundLocationUpdates

**Comment by johnnyshankman** [comment]
I currently do this to get around it. Maybe I'll make a pull request.

*In SOMotionDetector:*
```
- (void)updateLocationInBackgroundMode {
    [[SOLocationManager sharedInstance] setBackgroundUpdates: true];
}
```

*In SOLocationManager:*
```
- (void)setBackgroundUpdates:(bool)shouldUpdate {
    self.locationManager.allowsBackgroundLocationUpdates = shouldUpdate;
}
```

**Comment by AnthonyUccello** [comment]
Was this merged in?
