### ISSUE TITLE
Documentation not up to date?

### ISSUE THREAD

**Issue by ogezue** [SocialObjects-Software/SOMotionDetector#32]
In your documentation you write
`[SOLocationManager sharedInstance].allowsBackgroundLocationUpdates = YES;`

But I can't find this in code? The background mode is especially important for me.

**Comment by arturdev** [comment]
https://github.com/SocialObjects-Software/SOMotionDetector/blob/master/SOMotionDetector/SOLocationManager.h#L51

**Comment by ogezue** [comment]
thanks!
